### PR TITLE
Add missing group's predicate implementation

### PR DESCRIPTION
**Pull request by phoenleo**

### CODE REVIEW

**Review by grofit — APPROVED** [review]
I am baffled, as I thought that this was already implemented, as the whole point of `IHasPredicate` was to indicate that the group had a predicate that would be exposed, good catch... still very baffled, can only think I didnt merge the full branch with this work in when I was doing it.

**Comment by grofit** [comment]
Once I have run all tests I will do a minor release for this, thanks again for the PR.

**Comment by phoenleo** [comment]
@grofit thanks for approving my PR.
I really like your ECS implementation.
Do you have time discussing about ECS implementation in games?
Currently I'm struggling in finding a good rule of thumb when designing components.
And I am pretty troubled scaling the project using ECS.
Another problem I currently encounter is FSM and BT (Node Canvas) implementations.
Do you have any solutions regarding these matters?

I found this ECS - State Machine articles for Ash
http://www.richardlord.net/blog/ecs/finite-state-machines-with-ash.html

By the way, I would like to help you if you have any plan in making a big example project.

**Comment by grofit** [comment]
Hey, I am always happy to discuss tech etc but I would day join the gitter channel and we can discuss there as I have discussed ecs and bt/fsms before there with others so they can help discuss too.

**Pull request merged**
